// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ii4bttXstbtjoUVqPhEpwxxvxQsdti4',
    appId: '1:585920310721:web:ca0baf9091b9860589d340',
    messagingSenderId: '585920310721',
    projectId: 'woman-233fc',
    authDomain: 'woman-233fc.firebaseapp.com',
    storageBucket: 'woman-233fc.appspot.com',
    measurementId: 'G-20NN4N0HKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTEBK9IiAsZyh7Lgj0Tp0l6skmVvCHgbU',
    appId: '1:585920310721:android:d953f6809ef58fd889d340',
    messagingSenderId: '585920310721',
    projectId: 'woman-233fc',
    storageBucket: 'woman-233fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr_ppkwqMdrksNDWt6xajyCUfHLI4EKdM',
    appId: '1:585920310721:ios:574ea31b40c52bb889d340',
    messagingSenderId: '585920310721',
    projectId: 'woman-233fc',
    storageBucket: 'woman-233fc.appspot.com',
    iosBundleId: 'com.example.safeCircle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr_ppkwqMdrksNDWt6xajyCUfHLI4EKdM',
    appId: '1:585920310721:ios:574ea31b40c52bb889d340',
    messagingSenderId: '585920310721',
    projectId: 'woman-233fc',
    storageBucket: 'woman-233fc.appspot.com',
    iosBundleId: 'com.example.safeCircle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2ii4bttXstbtjoUVqPhEpwxxvxQsdti4',
    appId: '1:585920310721:web:2a6ef91b5f419e1089d340',
    messagingSenderId: '585920310721',
    projectId: 'woman-233fc',
    authDomain: 'woman-233fc.firebaseapp.com',
    storageBucket: 'woman-233fc.appspot.com',
    measurementId: 'G-DYNL7MVH72',
  );
}
