name: Build & Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Explicitly set permissions for creating releases

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Java setup with specific version
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Flutter setup with caching
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          architecture: x64
          cache: true # Enable Flutter cache

      # Check if there are any changes
      - name: Check for changes
        id: changes
        run: |
          git diff --quiet HEAD^ HEAD
          if [ $? -ne 0 ]; then
            echo "has_changes=true" >> $GITHUB_ENV
          else
            echo "has_changes=false" >> $GITHUB_ENV
          fi

      # Firebase options setup with error handling
      - name: Create Firebase Options
        if: env.has_changes == 'true'
        run: |
          if [ -z "${{ vars.FIREBASE_ANDROID_API_KEY }}" ] || \
             [ -z "${{ vars.FIREBASE_ANDROID_APP_ID }}" ] || \
             [ -z "${{ vars.FIREBASE_MESSAGING_SENDER_ID }}" ] || \
             [ -z "${{ vars.FIREBASE_PROJECT_ID }}" ] || \
             [ -z "${{ vars.FIREBASE_STORAGE_BUCKET }}" ]; then
            echo "Error: Missing required Firebase configuration variables"
            exit 1
          fi
          
          cat > lib/firebase_options.dart << 'EOL'
          // File generated by FlutterFire CLI.
          // ignore_for_file: type=lint
          import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
          import 'package:flutter/foundation.dart'
              show defaultTargetPlatform, kIsWeb, TargetPlatform;

          class DefaultFirebaseOptions {
            static FirebaseOptions get currentPlatform {
              if (kIsWeb) {
                throw UnsupportedError('Unsupported platform');
              }
              switch (defaultTargetPlatform) {
                case TargetPlatform.android:
                  return android;
                default:
                  throw UnsupportedError(
                    'DefaultFirebaseOptions are not supported for this platform.',
                  );
              }
            }

            static const FirebaseOptions android = FirebaseOptions(
              apiKey: '${{ vars.FIREBASE_ANDROID_API_KEY }}',
              appId: '${{ vars.FIREBASE_ANDROID_APP_ID }}',
              messagingSenderId: '${{ vars.FIREBASE_MESSAGING_SENDER_ID }}',
              projectId: '${{ vars.FIREBASE_PROJECT_ID }}',
              storageBucket: '${{ vars.FIREBASE_STORAGE_BUCKET }}',
            );
          }
          EOL

      # Install dependencies with retry
      - name: Install dependencies
        if: env.has_changes == 'true'
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: flutter pub get

      # Build steps
      - name: Build APK
        if: env.has_changes == 'true'
        run: flutter build apk --release --split-per-abi

      # Release step
      - name: Push to Releases
        if: env.has_changes == 'true'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
